import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Clase Lvl3: representa el primer nivel del juego.
 * Extiende la clase Level.
 * 
 * @author Noe & Miguel
 * @version 04/07/2023
 */
public class Lvl3 extends Level{
    
    private GreenfootSound music;
    /**
     * Constructor de la clase Lvl3.
     * Crea un nuevo nivel con el ancho y alto especificados, el fondo dado y la dificultad dada.
     * 
     * @param d La dificultad del nivel.
     */
    public Lvl3(int d){
        super(2000, 1200, 1, new GreenfootImage("Map004.png"), d);
        prepare();
        music = new GreenfootSound("Heartache.mp3");
        music.setVolume(18);
        music.playLoop();
    }
    /**
     * Constructor de la clase Lvl3.
     * Crea un nuevo nivel con el ancho y alto especificados, el fondo dado y la dificultad predeterminada.
     */
    public Lvl3(){
        super(2000, 1200, 1, new GreenfootImage("Map004.png"), 1);
        prepare();
        music = new GreenfootSound("Heartache.mp3");
        music.setVolume(18);
        music.playLoop();
    }
    /**
     * Obtiene la música del nivel.
     * 
     * @return El objeto GreenfootSound que representa la música del nivel.
     */
    public GreenfootSound getMusic(){
        return music;
    }
    /**
     * Prepara el nivel colocando los objetos y jugadores en posiciones iniciales.
     */
    private void prepare(){
        Player player = new Player();
        addObject(player,62,25);
        Player player2 = new Player();
        addObject(player2,58,137);
        Player player3 = new Player();
        addObject(player3,1444,713);

        Block block = new Block(120, 24);
        addObject(block, 60, 84);
        block = new Block(96, 24);
        addObject(block, 312, 84);
        block = new Block(216, 24);
        addObject(block, 756, 84);
        block = new Block(24, 24);
        addObject(block, 12, 108);
        block = new Block(408, 24);
        addObject(block, 1524, 108);
        block = new Block(96, 24);
        addObject(block, 1872, 108);
        block = new Block(24, 24);
        addObject(block, 12, 132);
        block = new Block(72, 24);
        addObject(block, 540, 132);
        block = new Block(24, 24);
        addObject(block, 1908, 132);
        block = new Block(24, 24);
        addObject(block, 12, 156);
        block = new Block(24, 24);
        addObject(block, 1908, 156);
        block = new Block(480, 24);
        addObject(block, 240, 180);
        block = new Block(312, 24);
        addObject(block, 1116, 180);
        block = new Block(24, 24);
        addObject(block, 1908, 180);
        block = new Block(24, 24);
        addObject(block, 1908, 204);
        block = new Block(24, 24);
        addObject(block, 1908, 228);
        block = new Block(1920, 24);
        addObject(block, 960, 276);
        block = new Block(144, 24);
        addObject(block, 288, 492);
        block = new Block(240, 24);
        addObject(block, 528, 492);
        block = new Block(336, 24);
        addObject(block, 936, 492);
        block = new Block(288, 24);
        addObject(block, 1344, 492);
        block = new Block(24, 24);
        addObject(block, 636, 516);
        block = new Block(24, 24);
        addObject(block, 780, 516);
        block = new Block(24, 24);
        addObject(block, 1092, 516);
        block = new Block(24, 24);
        addObject(block, 1212, 516);
        block = new Block(168, 24);
        addObject(block, 708, 540);
        block = new Block(144, 24);
        addObject(block, 1152, 540);
        block = new Block(432, 24);
        addObject(block, 1776, 540);
        block = new Block(168, 24);
        addObject(block, 84, 636);
        block = new Block(576, 24);
        addObject(block, 552, 708);
        block = new Block(312, 24);
        addObject(block, 1308, 756);
        block = new Block(432, 24);
        addObject(block, 1776, 756);
        block = new Block(216, 24);
        addObject(block, 996, 828);
        block = new Block(1992, 24);
        addObject(block, 996, 948);
        block = new Block(24, 24);
        addObject(block, 1908, 252);

        Obstacle peak = new Obstacle();
        addObject(peak, 732, 60);
        peak = new Obstacle();
        addObject(peak, 756, 60);
        peak = new Obstacle();
        addObject(peak, 1500, 84);
        peak = new Obstacle();
        addObject(peak, 1524, 84);
        peak = new Obstacle();
        addObject(peak, 1548, 84);
        peak = new Obstacle();
        addObject(peak, 180, 156);
        peak = new Obstacle();
        addObject(peak, 204, 156);
        peak = new Obstacle();
        addObject(peak, 1092, 156);
        peak = new Obstacle();
        addObject(peak, 1116, 156);
        peak = new Obstacle();
        addObject(peak, 1140, 156);
        peak = new Obstacle();
        addObject(peak, 12, 252);
        peak = new Obstacle();
        addObject(peak, 36, 252);
        peak = new Obstacle();
        addObject(peak, 60, 252);
        peak = new Obstacle();
        addObject(peak, 84, 252);
        peak = new Obstacle();
        addObject(peak, 108, 252);
        peak = new Obstacle();
        addObject(peak, 132, 252);
        peak = new Obstacle();
        addObject(peak, 156, 252);
        peak = new Obstacle();
        addObject(peak, 180, 252);
        peak = new Obstacle();
        addObject(peak, 204, 252);
        peak = new Obstacle();
        addObject(peak, 228, 252);
        peak = new Obstacle();
        addObject(peak, 252, 252);
        peak = new Obstacle();
        addObject(peak, 276, 252);
        peak = new Obstacle();
        addObject(peak, 300, 252);
        peak = new Obstacle();
        addObject(peak, 324, 252);
        peak = new Obstacle();
        addObject(peak, 348, 252);
        peak = new Obstacle();
        addObject(peak, 372, 252);
        peak = new Obstacle();
        addObject(peak, 396, 252);
        peak = new Obstacle();
        addObject(peak, 420, 252);
        peak = new Obstacle();
        addObject(peak, 444, 252);
        peak = new Obstacle();
        addObject(peak, 468, 252);
        peak = new Obstacle();
        addObject(peak, 492, 252);
        peak = new Obstacle();
        addObject(peak, 516, 252);
        peak = new Obstacle();
        addObject(peak, 540, 252);
        peak = new Obstacle();
        addObject(peak, 564, 252);
        peak = new Obstacle();
        addObject(peak, 588, 252);
        peak = new Obstacle();
        addObject(peak, 612, 252);
        peak = new Obstacle();
        addObject(peak, 636, 252);
        peak = new Obstacle();
        addObject(peak, 660, 252);
        peak = new Obstacle();
        addObject(peak, 684, 252);
        peak = new Obstacle();
        addObject(peak, 708, 252);
        peak = new Obstacle();
        addObject(peak, 732, 252);
        peak = new Obstacle();
        addObject(peak, 756, 252);
        peak = new Obstacle();
        addObject(peak, 780, 252);
        peak = new Obstacle();
        addObject(peak, 804, 252);
        peak = new Obstacle();
        addObject(peak, 828, 252);
        peak = new Obstacle();
        addObject(peak, 852, 252);
        peak = new Obstacle();
        addObject(peak, 876, 252);
        peak = new Obstacle();
        addObject(peak, 900, 252);
        peak = new Obstacle();
        addObject(peak, 924, 252);
        peak = new Obstacle();
        addObject(peak, 948, 252);
        peak = new Obstacle();
        addObject(peak, 972, 252);
        peak = new Obstacle();
        addObject(peak, 996, 252);
        peak = new Obstacle();
        addObject(peak, 1020, 252);
        peak = new Obstacle();
        addObject(peak, 1044, 252);
        peak = new Obstacle();
        addObject(peak, 1068, 252);
        peak = new Obstacle();
        addObject(peak, 1092, 252);
        peak = new Obstacle();
        addObject(peak, 1116, 252);
        peak = new Obstacle();
        addObject(peak, 1140, 252);
        peak = new Obstacle();
        addObject(peak, 1164, 252);
        peak = new Obstacle();
        addObject(peak, 1188, 252);
        peak = new Obstacle();
        addObject(peak, 1212, 252);
        peak = new Obstacle();
        addObject(peak, 1236, 252);
        peak = new Obstacle();
        addObject(peak, 1260, 252);
        peak = new Obstacle();
        addObject(peak, 1284, 252);
        peak = new Obstacle();
        addObject(peak, 1308, 252);
        peak = new Obstacle();
        addObject(peak, 1332, 252);
        peak = new Obstacle();
        addObject(peak, 1356, 252);
        peak = new Obstacle();
        addObject(peak, 1380, 252);
        peak = new Obstacle();
        addObject(peak, 1404, 252);
        peak = new Obstacle();
        addObject(peak, 1428, 252);
        peak = new Obstacle();
        addObject(peak, 1452, 252);
        peak = new Obstacle();
        addObject(peak, 1476, 252);
        peak = new Obstacle();
        addObject(peak, 1500, 252);
        peak = new Obstacle();
        addObject(peak, 1524, 252);
        peak = new Obstacle();
        addObject(peak, 1548, 252);
        peak = new Obstacle();
        addObject(peak, 1572, 252);
        peak = new Obstacle();
        addObject(peak, 1596, 252);
        peak = new Obstacle();
        addObject(peak, 1620, 252);
        peak = new Obstacle();
        addObject(peak, 1644, 252);
        peak = new Obstacle();
        addObject(peak, 1668, 252);
        peak = new Obstacle();
        addObject(peak, 1692, 252);
        peak = new Obstacle();
        addObject(peak, 1716, 252);
        peak = new Obstacle();
        addObject(peak, 1740, 252);
        peak = new Obstacle();
        addObject(peak, 1764, 252);
        peak = new Obstacle();
        addObject(peak, 1788, 252);
        peak = new Obstacle();
        addObject(peak, 1812, 252);
        peak = new Obstacle();
        addObject(peak, 1836, 252);
        peak = new Obstacle();
        addObject(peak, 1860, 252);
        peak = new Obstacle();
        addObject(peak, 1884, 252);

        peak = new Obstacle();
        addObject(peak, 492, 468);
        peak = new Obstacle();
        addObject(peak, 516, 468);
        peak = new Obstacle();
        addObject(peak, 924, 468);
        peak = new Obstacle();
        addObject(peak, 948, 468);
        peak = new Obstacle();
        addObject(peak, 972, 468);
        peak = new Obstacle();
        addObject(peak, 1332, 468);
        peak = new Obstacle();
        addObject(peak, 1356, 468);
        peak = new Obstacle();
        addObject(peak, 372, 516);
        peak = new Obstacle();
        addObject(peak, 396, 516);
        peak = new Obstacle();
        addObject(peak, 684, 516);
        peak = new Obstacle();
        addObject(peak, 660, 516);
        peak = new Obstacle();
        addObject(peak, 708, 516);
        peak = new Obstacle();
        addObject(peak, 732, 516);
        peak = new Obstacle();
        addObject(peak, 756, 516);
        peak = new Obstacle();
        addObject(peak, 1116, 516);
        peak = new Obstacle();
        addObject(peak, 1140, 516);
        peak = new Obstacle();
        addObject(peak, 1164, 516);
        peak = new Obstacle();
        addObject(peak, 1188, 516);
        peak = new Obstacle();
        addObject(peak, 1740, 516);
        peak = new Obstacle();
        addObject(peak, 1764, 516);
        peak = new Obstacle();
        addObject(peak, 1788, 516);
        peak = new Obstacle();
        addObject(peak, 1812, 516);
        peak = new Obstacle();
        addObject(peak, 444, 684);
        peak = new Obstacle();
        addObject(peak, 468, 684);
        peak = new Obstacle();
        addObject(peak, 492, 684);
        peak = new Obstacle();
        addObject(peak, 684, 684);
        peak = new Obstacle();
        addObject(peak, 708, 684);
        peak = new Obstacle();
        addObject(peak, 1284, 732);
        peak = new Obstacle();
        addObject(peak, 1308, 732);
        peak = new Obstacle();
        addObject(peak, 1332, 732);
        peak = new Obstacle();
        addObject(peak, 1716, 732);
        peak = new Obstacle();
        addObject(peak, 1740, 732);
        peak = new Obstacle();
        addObject(peak, 1764, 732);
        peak = new Obstacle();
        addObject(peak, 1788, 732);
        peak = new Obstacle();
        addObject(peak, 996, 804);
        peak = new Obstacle();
        addObject(peak, 1020, 804);
        peak = new Obstacle();
        addObject(peak, 12, 924);
        peak = new Obstacle();
        addObject(peak, 36, 924);
        peak = new Obstacle();
        addObject(peak, 60, 924);
        peak = new Obstacle();
        addObject(peak, 84, 924);
        peak = new Obstacle();
        addObject(peak, 108, 924);
        peak = new Obstacle();
        addObject(peak, 132, 924);
        peak = new Obstacle();
        addObject(peak, 156, 924);
        peak = new Obstacle();
        addObject(peak, 180, 924);
        peak = new Obstacle();
        addObject(peak, 204, 924);
        peak = new Obstacle();
        addObject(peak, 228, 924);
        peak = new Obstacle();
        addObject(peak, 252, 924);
        peak = new Obstacle();
        addObject(peak, 276, 924);
        peak = new Obstacle();
        addObject(peak, 300, 924);
        peak = new Obstacle();
        addObject(peak, 324, 924);
        peak = new Obstacle();
        addObject(peak, 348, 924);
        peak = new Obstacle();
        addObject(peak, 372, 924);
        peak = new Obstacle();
        addObject(peak, 396, 924);
        peak = new Obstacle();
        addObject(peak, 420, 924);
        peak = new Obstacle();
        addObject(peak, 444, 924);
        peak = new Obstacle();
        addObject(peak, 468, 924);
        peak = new Obstacle();
        addObject(peak, 492, 924);
        peak = new Obstacle();
        addObject(peak, 516, 924);
        peak = new Obstacle();
        addObject(peak, 540, 924);
        peak = new Obstacle();
        addObject(peak, 564, 924);
        peak = new Obstacle();
        addObject(peak, 588, 924);
        peak = new Obstacle();
        addObject(peak, 612, 924);
        peak = new Obstacle();
        addObject(peak, 636, 924);
        peak = new Obstacle();
        addObject(peak, 660, 924);
        peak = new Obstacle();
        addObject(peak, 684, 924);
        peak = new Obstacle();
        addObject(peak, 708, 924);
        peak = new Obstacle();
        addObject(peak, 732, 924);
        peak = new Obstacle();
        addObject(peak, 756, 924);
        peak = new Obstacle();
        addObject(peak, 780, 924);
        peak = new Obstacle();
        addObject(peak, 804, 924);
        peak = new Obstacle();
        addObject(peak, 828, 924);
        peak = new Obstacle();
        addObject(peak, 852, 924);
        peak = new Obstacle();
        addObject(peak, 876, 924);
        peak = new Obstacle();
        addObject(peak, 900, 924);
        peak = new Obstacle();
        addObject(peak, 924, 924);
        peak = new Obstacle();
        addObject(peak, 948, 924);
        peak = new Obstacle();
        addObject(peak, 972, 924);
        peak = new Obstacle();
        addObject(peak, 996, 924);
        peak = new Obstacle();
        addObject(peak, 1020, 924);
        peak = new Obstacle();
        addObject(peak, 1044, 924);
        peak = new Obstacle();
        addObject(peak, 1068, 924);
        peak = new Obstacle();
        addObject(peak, 1092, 924);
        peak = new Obstacle();
        addObject(peak, 1116, 924);
        peak = new Obstacle();
        addObject(peak, 1140, 924);
        peak = new Obstacle();
        addObject(peak, 1164, 924);
        peak = new Obstacle();
        addObject(peak, 1188, 924);
        peak = new Obstacle();
        addObject(peak, 1212, 924);
        peak = new Obstacle();
        addObject(peak, 1236, 924);
        peak = new Obstacle();
        addObject(peak, 1260, 924);
        peak = new Obstacle();
        addObject(peak, 1284, 924);
        peak = new Obstacle();
        addObject(peak, 1308, 924);
        peak = new Obstacle();
        addObject(peak, 1332, 924);
        peak = new Obstacle();
        addObject(peak, 1356, 924);
        peak = new Obstacle();
        addObject(peak, 1380, 924);
        peak = new Obstacle();
        addObject(peak, 1404, 924);
        peak = new Obstacle();
        addObject(peak, 1428, 924);
        peak = new Obstacle();
        addObject(peak, 1452, 924);
        peak = new Obstacle();
        addObject(peak, 1476, 924);
        peak = new Obstacle();
        addObject(peak, 1500, 924);
        peak = new Obstacle();
        addObject(peak, 1524, 924);
        peak = new Obstacle();
        addObject(peak, 1548, 924);
        peak = new Obstacle();
        addObject(peak, 1572, 924);
        peak = new Obstacle();
        addObject(peak, 1596, 924);
        peak = new Obstacle();
        addObject(peak, 1620, 924);
        peak = new Obstacle();
        addObject(peak, 1644, 924);
        peak = new Obstacle();
        addObject(peak, 1668, 924);
        peak = new Obstacle();
        addObject(peak, 1692, 924);
        peak = new Obstacle();
        addObject(peak, 1716, 924);
        peak = new Obstacle();
        addObject(peak, 1740, 924);
        peak = new Obstacle();
        addObject(peak, 1764, 924);
        peak = new Obstacle();
        addObject(peak, 1788, 924);
        peak = new Obstacle();
        addObject(peak, 1812, 924);
        peak = new Obstacle();
        addObject(peak, 1836, 924);
        peak = new Obstacle();
        addObject(peak, 1860, 924);
        peak = new Obstacle();
        addObject(peak, 1884, 924);
        peak = new Obstacle();
        addObject(peak, 1908, 924);
        peak = new Obstacle();
        addObject(peak, 1932, 924);
        peak = new Obstacle();
        addObject(peak, 1956, 924);
        peak = new Obstacle();
        addObject(peak, 1980, 924);
        Orb orb = new Orb();
        addObject(orb, 156, 36);
        orb = new Orb();
        addObject(orb, 324, 36);
        orb = new Orb();
        addObject(orb, 612, 36);
        orb = new Orb();
        addObject(orb, 828, 36);
        orb = new Orb();
        addObject(orb, 924, 36);
        orb = new Orb();
        addObject(orb, 1524, 36);
        orb = new Orb();
        addObject(orb, 1764, 36);
        orb = new Orb();
        addObject(orb, 516, 60);
        orb = new Orb();
        addObject(orb, 1116, 60);
        orb = new Orb();
        addObject(orb, 1356, 60);
        orb = new Orb();
        addObject(orb, 1668, 60);
        orb = new Orb();
        addObject(orb, 1884, 60);
        orb = new Orb();
        addObject(orb, 228, 84);
        orb = new Orb();
        addObject(orb, 420, 84);
        orb = new Orb();
        addObject(orb, 972, 108);
        orb = new Orb();
        addObject(orb, 1212, 108);
        orb = new Orb();
        addObject(orb, 324, 132);
        orb = new Orb();
        addObject(orb, 1956, 132);
        orb = new Orb();
        addObject(orb, 1956, 204);
        orb = new Orb();
        addObject(orb, 1956, 276);
        orb = new Orb();
        addObject(orb, 1956, 348);
        orb = new Orb();
        addObject(orb, 156, 372);
        orb = new Orb();
        addObject(orb, 948, 372);
        orb = new Orb();
        addObject(orb, 1332, 372);
        orb = new Orb();
        addObject(orb, 516, 396);
        orb = new Orb();
        addObject(orb, 708, 396);
        orb = new Orb();
        addObject(orb, 1140, 396);
        orb = new Orb();
        addObject(orb, 1476, 396);
        orb = new Orb();
        addObject(orb, 228, 420);
        orb = new Orb();
        addObject(orb, 636, 420);
        orb = new Orb();
        addObject(orb, 780, 420);
        orb = new Orb();
        addObject(orb, 852, 420);
        orb = new Orb();
        addObject(orb, 1044, 420);
        orb = new Orb();
        addObject(orb, 1236, 420);
        orb = new Orb();
        addObject(orb, 1716, 420);
        orb = new Orb();
        addObject(orb, 1812, 420);
        orb = new Orb();
        addObject(orb, 1956, 420);
        orb = new Orb();
        addObject(orb, 108, 444);
        orb = new Orb();
        addObject(orb, 324, 444);
        orb = new Orb();
        addObject(orb, 444, 444);
        orb = new Orb();
        addObject(orb, 1548, 444);
        orb = new Orb();
        addObject(orb, 108, 516);
        orb = new Orb();
        addObject(orb, 228, 564);
        orb = new Orb();
        addObject(orb, 708, 588);
        orb = new Orb();
        addObject(orb, 444, 612);
        orb = new Orb();
        addObject(orb, 300, 636);
        orb = new Orb();
        addObject(orb, 564, 636);
        orb = new Orb();
        addObject(orb, 804, 636);
        orb = new Orb();
        addObject(orb, 1524, 636);
        orb = new Orb();
        addObject(orb, 1116, 660);
        orb = new Orb();
        addObject(orb, 1284, 660);
        orb = new Orb();
        addObject(orb, 1452, 660);
        orb = new Orb();
        addObject(orb, 900, 684);
        orb = new Orb();
        addObject(orb, 1188, 684);
        orb = new Orb();
        addObject(orb, 1380, 684);
        orb = new Orb();
        addObject(orb, 1572, 684);
        orb = new Orb();
        addObject(orb, 1644, 708);
        orb = new Orb();
        addObject(orb, 1068, 732);
        orb = new Orb();
        addObject(orb, 900, 756);

        Laser laser1 = new Laser(72 , "Blue");
        addObject(laser1, 108, 132);
        Laser laser2 = new Laser(240, "Red");
        addObject(laser2, 1620, 408);
        Laser laser3 = new Laser(312, "Yellow");
        addObject(laser3, 948, 660);

        PushButton pushButton = new PushButton(laser1, "Blue");
        addObject(pushButton, 828, 468);
        pushButton = new PushButton(laser3, "Yellow");
        addObject(pushButton, 1884, 516);
        pushButton = new PushButton(laser2, "Red");
        addObject(pushButton, 84, 612);

        Finish finish = new Finish();
        addObject(finish,1952,700);
    }
}
